spring:

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: "factory-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          OrderCreatedEvent:com.veteroch4k.factory_service.models.events.OrderCreatedEvent,
          MaterialReservedEvent:com.veteroch4k.factory_service.models.events.MaterialReservedEvent,
          ToolReservedEvent:com.veteroch4k.factory_service.models.events.ToolReservedEvent
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          MaterialReservationCommand:com.veteroch4k.factory_service.models.commands.MaterialReservationCommand,
          ToolReservationCommand:com.veteroch4k.factory_service.models.commands.ToolReservationCommand

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/firm_prod_db?currentSchema=factory_service
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.migrations-master.yaml
    enabled: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8181}/realms/firm-realm


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8070}/eureka/

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true