spring:

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "factory-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.veteroch4k.factory_service.models.OrderCreatedEvent

  datasource:
    url: jdbc:postgresql://localhost:5433/firm_prod_db?currentSchema=factory_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.migrations-master.yaml
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true