spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/firm_prod_db?currentSchema=toolwarehouse_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "warehouse-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          ToolReservationCommand:com.veteroch4k.toolwarehouse.models.commands.ToolReservationCommand
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          ToolReservedEvent:com.veteroch4k.toolwarehouse.models.ToolReservedEvent

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.migrations-master.yaml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/



server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true





