spring:
  application:
    name: warehouse-service

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/firm_prod_db?currentSchema=warehouse_service
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: "warehouse-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          MaterialReservationCommand:com.veteroch4k.warehouse.models.commands.MaterialReservationCommand
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          MaterialReservedEvent:com.veteroch4k.warehouse.models.MaterialReservedEvent

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.migrations-master.yaml

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8181}/realms/firm-realm/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8070}/eureka/

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true