spring:
  application:
    name: warehouse-service

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5433/firm_prod_db?currentSchema=warehouse_service
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.migrations-master.yaml

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/



server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true