spring:
  application:
    name: employers-service
  profiles:
    active: default

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8071}


resilience4j.circuitbreaker:
  instances:
    test:
      registerHealthIndicator: true  # Для актуатора /health
      slidingWindowType: COUNT_BASED  # Тип окна (COUNT_BASED или TIME_BASED)
      slidingWindowSize: 10  # Размер окна для анализа ошибок
      minimumNumberOfCalls: 5  # Мин. вызовов перед проверкой
      failureRateThreshold: 5  # % ошибок для размыкания
      waitDurationInOpenState: 10s  # Время в OPEN перед переходом в HALF-OPEN
      permittedNumberOfCallsInHalfOpenState: 3  # Вызовов в HALF-OPEN
      automaticTransitionFromOpenToHalfOpenEnabled: true  # Автопереход
      recordExceptions:  # Какие исключения считать ошибками
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:  # Какие исключения игнорировать
        - org.springframework.web.client.HttpClientErrorException

resilience4j:
  bulkhead:
    instances:
      bulkheadTest:
        max-wait-duration: 100ms
        max-concurrent-calls: 20

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadPoolTest:
      maxThreadPoolSize: 10
      coreThreadPoolSize: 5
      queueCapacity: 20

resilience4j.retry:
  instances:
    retryTest:
      max-attempts: 5
      wait-duration: 100ms
      retry-exceptions:
        - java.util.concurrent.TimeoutException
